[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; font-src 'self' https://fonts.googleapis.con ;  script-src 'self' https://miro.com"
    X-Content-Type-Options = "nosniff"